#!/usr/bin/env bash

time mcvine instruments arcs nxs reduce sim.nxs --qaxis=${QAXIS} --tof2E
mcvine mantid extract_iqe iqe.nxs iqe.h5
# python -c "import histogram.hdf as hh; iqe=hh.load('iqe.h5'); iq=iqe.sum('energy'); hh.dump(iq, 'iq.h5'); ie = iqe[(2.5,9), ()].sum('Q'); hh.dump(ie, 'ie-Q_2.5,9.h5')"
