#!/usr/bin/env bash

LAUNCHER=`mcvine mpi launcher`
rm -rf out && ./sss --ncount=1e5 --multiple-scattering=on --$LAUNCHER.nodes=2 --buffer_size=10000

#--journal.debug.phonon_incoherent_inelastic_kernel
