#!/usr/bin/env bash

LAUNCHER=`mcvine mpi launcher`
rm -rf out && time ./sss --ncount=1e6 --$LAUNCHER.nodes=5

#--journal.debug.phonon_incoherent_inelastic_kernel

# rm -rf out && ./sss --ncount=1e8  --$LAUNCHER.nodes=10 

