sudo: true
# dist: trusty

language: python

python:
  - 2.7

branches:
  only:
    - master

before_install:
  - sudo apt-get install -y freeglut3-dev libglu1-mesa
  - if [[ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]]; then wget http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH
  - git clone https://github.com/yxqd/dotmantid ~/.mantid

install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - export GIT_VER=`git describe --tags`
  - export VERSION=`python -c "print '$GIT_VER'.split('-')[0][1:]"`
  - echo ${TRAVIS_PYTHON_VERSION}
  - ./builders/travis/build.sh
  - # conda install -n root conda-build
  - # conda install -n testenv anaconda-client
  - # conda config --set anaconda_upload no

script:
  - cd build
  - CTEST_OUTPUT_ON_FAILURE=1 make test

notifications:
  email:
    on_success: change
    on_failure: always
