#!/usr/bin/env bash

ln -s fornxs/ARCSinfo-cache/pixelID2position.bin
ln -s fornxs/ARCSinfo-cache/solidangles.bin

arcs-events2iqe-directly -events=work-arcs-neutrons2nxs/todetsys/out/events.dat --tofbinsize=0.1 --Ei=75.44 --Eaxis=-70,70,1. --Qaxis=0,11,0.1 --pixelpositionsfile=pixelID2position.bin --out=iqe-direct.h5


python -c "import histogram.hdf as hh; iqe=hh.load('iqe-direct.h5'); ie = iqe.sum('Q'); hh.dump(ie, 'ie-direct.h5')"

