#!/usr/bin/env bash
echo $SAMPLE_ANGLE

LAUNCHER=`mcvine mpi launcher`

SSSCMD="./sss --ncount=${NCOUNT} --buffer_size=${BUFFER_SIZE} --$LAUNCHER.nodes=${NODES} --multiple-scattering=${MS} --geometer.sample=(0,0,0),(0,${SAMPLE_ANGLE},0)"

echo $SSSCMD
rm -rf out && time $SSSCMD
