#!/usr/bin/env bash

LAUNCHER=`mcvine mpi launcher`
rm -rf out && ./sss --ncount=${NCOUNT} --$LAUNCHER.nodes=${NODES} --buffer_size=${BUFFER_SIZE} \
		    --multiple-scattering=${MULSCATT}

#--journal.debug.phonon_incoherent_inelastic_kernel
