name: CI

env: {}

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "00 02 * * *"

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.7"]   
    steps:
      - name: install glut
        run: sudo apt-get update && sudo apt-get install -y freeglut3-dev libglu1-mesa

      - name: Check out source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: ~/.mantid
        run: git clone https://github.com/yxqd/dotmantid ~/.mantid

      # setup conda
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: test
          python-version: ${{ matrix.python-version }}
          channels: mcvine/label/unstable,mcvine,mantid/label/nightly,mantid,diffpy,conda-forge
      
      # install deps and build
      - name: install / build / test
        shell: pwsh
        run: |
          conda install mcvine.instruments mpich
          mcvine
          ./builders/github-actions/build_and_test.sh
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}

      - name: conda build and upload
        shell: pwsh
        run: |
          ./builders/github-actions/conda_build_and_upload.sh
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
          CONDA_UPLOAD_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
